apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-m6qx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-m6qx
    app.kubernetes.io/part-of: integ-app-ipfa
  name: hacbs-test-project-m6qx
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-m6qx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-m6qx
    spec:
      containers:
      - image: quay.io/mbasti-test-org/integration1-barm-tenant/integ-app-ipfa/hacbs-test-project-m6qx@sha256:8bff18ed3563dbf841790a9a875e45127de2da9f5ed995acaafb64b0e0d0770b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
